[package]
name = "tmr"
version = "0.1.0"
authors = ["Sam Miller <sam.r.miller1@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "tmr"
path = "src/bin/tmr.rs"